<?php

namespace Container37oEEWb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MIJcwTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MIJcw_T' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MIJcw_T'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'projetsEtat' => ['privates', '.errored..service_locator.MIJcw_T.App\\Entity\\ProjetsEtat', NULL, 'Cannot autowire service ".service_locator.MIJcw_T": it needs an instance of "App\\Entity\\ProjetsEtat" but this type has been excluded in "config/services.yaml".'],
        ], [
            'projetsEtat' => 'App\\Entity\\ProjetsEtat',
        ]);
    }
}
