<?php

namespace Container37oEEWb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProjetsEtapesControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fRPJURf.App\Controller\ProjetsEtapesController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fRPJURf.App\\Controller\\ProjetsEtapesController::show()'] = ($container->privates['.service_locator.fRPJURf'] ?? $container->load('get_ServiceLocator_FRPJURfService'))->withContext('App\\Controller\\ProjetsEtapesController::show()', $container);
    }
}
