<?php

namespace Container37oEEWb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProjetsEtatControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MIJcw_T.App\Controller\ProjetsEtatController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MIJcw_T.App\\Controller\\ProjetsEtatController::edit()'] = ($container->privates['.service_locator.MIJcw_T'] ?? $container->load('get_ServiceLocator_MIJcwTService'))->withContext('App\\Controller\\ProjetsEtatController::edit()', $container);
    }
}
