<?php

namespace ContainerD5OMkT4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JPfugqEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JPfugqE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JPfugqE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'client' => ['privates', '.errored..service_locator.JPfugqE.App\\Entity\\Clients', NULL, 'Cannot autowire service ".service_locator.JPfugqE": it needs an instance of "App\\Entity\\Clients" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'client' => 'App\\Entity\\Clients',
        ]);
    }
}
