<?php

namespace ContainerD5OMkT4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FRPJURfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fRPJURf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fRPJURf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'projetsEtape' => ['privates', '.errored..service_locator.fRPJURf.App\\Entity\\ProjetsEtapes', NULL, 'Cannot autowire service ".service_locator.fRPJURf": it needs an instance of "App\\Entity\\ProjetsEtapes" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'projetsEtape' => 'App\\Entity\\ProjetsEtapes',
        ]);
    }
}
