<?php

namespace ContainerD5OMkT4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OLuvPavService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oLuvPav' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oLuvPav'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\ClientsController::show' => ['privates', '.service_locator.JPfugqE.App\\Controller\\ClientsController::show()', 'getClientsControllershowService', true],
            'App\\Controller\\ClientsController::edit' => ['privates', '.service_locator.JPfugqE.App\\Controller\\ClientsController::edit()', 'getClientsControllereditService', true],
            'App\\Controller\\ClientsController::delete' => ['privates', '.service_locator.JPfugqE.App\\Controller\\ClientsController::delete()', 'getClientsControllerdeleteService', true],
            'App\\Controller\\DocumentsController::index' => ['privates', '.service_locator.pGe727G.App\\Controller\\DocumentsController::index()', 'getDocumentsControllerindexService', true],
            'App\\Controller\\DocumentsController::show' => ['privates', '.service_locator.XqlcQlt.App\\Controller\\DocumentsController::show()', 'getDocumentsControllershowService', true],
            'App\\Controller\\DocumentsController::edit' => ['privates', '.service_locator.XqlcQlt.App\\Controller\\DocumentsController::edit()', 'getDocumentsControllereditService', true],
            'App\\Controller\\DocumentsController::delete' => ['privates', '.service_locator.XqlcQlt.App\\Controller\\DocumentsController::delete()', 'getDocumentsControllerdeleteService', true],
            'App\\Controller\\EtapesController::show' => ['privates', '.service_locator.iBo63Wb.App\\Controller\\EtapesController::show()', 'getEtapesControllershowService', true],
            'App\\Controller\\EtapesController::edit' => ['privates', '.service_locator.iBo63Wb.App\\Controller\\EtapesController::edit()', 'getEtapesControllereditService', true],
            'App\\Controller\\EtapesController::delete' => ['privates', '.service_locator.iBo63Wb.App\\Controller\\EtapesController::delete()', 'getEtapesControllerdeleteService', true],
            'App\\Controller\\ProjetsController::show' => ['privates', '.service_locator.scWB.EP.App\\Controller\\ProjetsController::show()', 'getProjetsControllershowService', true],
            'App\\Controller\\ProjetsController::edit' => ['privates', '.service_locator.scWB.EP.App\\Controller\\ProjetsController::edit()', 'getProjetsControllereditService', true],
            'App\\Controller\\ProjetsController::delete' => ['privates', '.service_locator.scWB.EP.App\\Controller\\ProjetsController::delete()', 'getProjetsControllerdeleteService', true],
            'App\\Controller\\ProjetsEtapesController::show' => ['privates', '.service_locator.fRPJURf.App\\Controller\\ProjetsEtapesController::show()', 'getProjetsEtapesControllershowService', true],
            'App\\Controller\\ProjetsEtapesController::edit' => ['privates', '.service_locator.fRPJURf.App\\Controller\\ProjetsEtapesController::edit()', 'getProjetsEtapesControllereditService', true],
            'App\\Controller\\ProjetsEtapesController::delete' => ['privates', '.service_locator.fRPJURf.App\\Controller\\ProjetsEtapesController::delete()', 'getProjetsEtapesControllerdeleteService', true],
            'App\\Controller\\ProjetsEtatController::show' => ['privates', '.service_locator.MIJcw_T.App\\Controller\\ProjetsEtatController::show()', 'getProjetsEtatControllershowService', true],
            'App\\Controller\\ProjetsEtatController::edit' => ['privates', '.service_locator.MIJcw_T.App\\Controller\\ProjetsEtatController::edit()', 'getProjetsEtatControllereditService', true],
            'App\\Controller\\ProjetsEtatController::delete' => ['privates', '.service_locator.MIJcw_T.App\\Controller\\ProjetsEtatController::delete()', 'getProjetsEtatControllerdeleteService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\ClientsController:show' => ['privates', '.service_locator.JPfugqE.App\\Controller\\ClientsController::show()', 'getClientsControllershowService', true],
            'App\\Controller\\ClientsController:edit' => ['privates', '.service_locator.JPfugqE.App\\Controller\\ClientsController::edit()', 'getClientsControllereditService', true],
            'App\\Controller\\ClientsController:delete' => ['privates', '.service_locator.JPfugqE.App\\Controller\\ClientsController::delete()', 'getClientsControllerdeleteService', true],
            'App\\Controller\\DocumentsController:index' => ['privates', '.service_locator.pGe727G.App\\Controller\\DocumentsController::index()', 'getDocumentsControllerindexService', true],
            'App\\Controller\\DocumentsController:show' => ['privates', '.service_locator.XqlcQlt.App\\Controller\\DocumentsController::show()', 'getDocumentsControllershowService', true],
            'App\\Controller\\DocumentsController:edit' => ['privates', '.service_locator.XqlcQlt.App\\Controller\\DocumentsController::edit()', 'getDocumentsControllereditService', true],
            'App\\Controller\\DocumentsController:delete' => ['privates', '.service_locator.XqlcQlt.App\\Controller\\DocumentsController::delete()', 'getDocumentsControllerdeleteService', true],
            'App\\Controller\\EtapesController:show' => ['privates', '.service_locator.iBo63Wb.App\\Controller\\EtapesController::show()', 'getEtapesControllershowService', true],
            'App\\Controller\\EtapesController:edit' => ['privates', '.service_locator.iBo63Wb.App\\Controller\\EtapesController::edit()', 'getEtapesControllereditService', true],
            'App\\Controller\\EtapesController:delete' => ['privates', '.service_locator.iBo63Wb.App\\Controller\\EtapesController::delete()', 'getEtapesControllerdeleteService', true],
            'App\\Controller\\ProjetsController:show' => ['privates', '.service_locator.scWB.EP.App\\Controller\\ProjetsController::show()', 'getProjetsControllershowService', true],
            'App\\Controller\\ProjetsController:edit' => ['privates', '.service_locator.scWB.EP.App\\Controller\\ProjetsController::edit()', 'getProjetsControllereditService', true],
            'App\\Controller\\ProjetsController:delete' => ['privates', '.service_locator.scWB.EP.App\\Controller\\ProjetsController::delete()', 'getProjetsControllerdeleteService', true],
            'App\\Controller\\ProjetsEtapesController:show' => ['privates', '.service_locator.fRPJURf.App\\Controller\\ProjetsEtapesController::show()', 'getProjetsEtapesControllershowService', true],
            'App\\Controller\\ProjetsEtapesController:edit' => ['privates', '.service_locator.fRPJURf.App\\Controller\\ProjetsEtapesController::edit()', 'getProjetsEtapesControllereditService', true],
            'App\\Controller\\ProjetsEtapesController:delete' => ['privates', '.service_locator.fRPJURf.App\\Controller\\ProjetsEtapesController::delete()', 'getProjetsEtapesControllerdeleteService', true],
            'App\\Controller\\ProjetsEtatController:show' => ['privates', '.service_locator.MIJcw_T.App\\Controller\\ProjetsEtatController::show()', 'getProjetsEtatControllershowService', true],
            'App\\Controller\\ProjetsEtatController:edit' => ['privates', '.service_locator.MIJcw_T.App\\Controller\\ProjetsEtatController::edit()', 'getProjetsEtatControllereditService', true],
            'App\\Controller\\ProjetsEtatController:delete' => ['privates', '.service_locator.MIJcw_T.App\\Controller\\ProjetsEtatController::delete()', 'getProjetsEtatControllerdeleteService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\ClientsController::show' => '?',
            'App\\Controller\\ClientsController::edit' => '?',
            'App\\Controller\\ClientsController::delete' => '?',
            'App\\Controller\\DocumentsController::index' => '?',
            'App\\Controller\\DocumentsController::show' => '?',
            'App\\Controller\\DocumentsController::edit' => '?',
            'App\\Controller\\DocumentsController::delete' => '?',
            'App\\Controller\\EtapesController::show' => '?',
            'App\\Controller\\EtapesController::edit' => '?',
            'App\\Controller\\EtapesController::delete' => '?',
            'App\\Controller\\ProjetsController::show' => '?',
            'App\\Controller\\ProjetsController::edit' => '?',
            'App\\Controller\\ProjetsController::delete' => '?',
            'App\\Controller\\ProjetsEtapesController::show' => '?',
            'App\\Controller\\ProjetsEtapesController::edit' => '?',
            'App\\Controller\\ProjetsEtapesController::delete' => '?',
            'App\\Controller\\ProjetsEtatController::show' => '?',
            'App\\Controller\\ProjetsEtatController::edit' => '?',
            'App\\Controller\\ProjetsEtatController::delete' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\ClientsController:show' => '?',
            'App\\Controller\\ClientsController:edit' => '?',
            'App\\Controller\\ClientsController:delete' => '?',
            'App\\Controller\\DocumentsController:index' => '?',
            'App\\Controller\\DocumentsController:show' => '?',
            'App\\Controller\\DocumentsController:edit' => '?',
            'App\\Controller\\DocumentsController:delete' => '?',
            'App\\Controller\\EtapesController:show' => '?',
            'App\\Controller\\EtapesController:edit' => '?',
            'App\\Controller\\EtapesController:delete' => '?',
            'App\\Controller\\ProjetsController:show' => '?',
            'App\\Controller\\ProjetsController:edit' => '?',
            'App\\Controller\\ProjetsController:delete' => '?',
            'App\\Controller\\ProjetsEtapesController:show' => '?',
            'App\\Controller\\ProjetsEtapesController:edit' => '?',
            'App\\Controller\\ProjetsEtapesController:delete' => '?',
            'App\\Controller\\ProjetsEtatController:show' => '?',
            'App\\Controller\\ProjetsEtatController:edit' => '?',
            'App\\Controller\\ProjetsEtatController:delete' => '?',
        ]);
    }
}
