<?php

namespace ContainerD5OMkT4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ScWB_EPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.scWB.EP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.scWB.EP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'projet' => ['privates', '.errored..service_locator.scWB.EP.App\\Entity\\Projets', NULL, 'Cannot autowire service ".service_locator.scWB.EP": it needs an instance of "App\\Entity\\Projets" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'projet' => 'App\\Entity\\Projets',
        ]);
    }
}
