<?php

namespace ContainerD5OMkT4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XqlcQltService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XqlcQlt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XqlcQlt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'document' => ['privates', '.errored..service_locator.XqlcQlt.App\\Entity\\Documents', NULL, 'Cannot autowire service ".service_locator.XqlcQlt": it needs an instance of "App\\Entity\\Documents" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'document' => 'App\\Entity\\Documents',
        ]);
    }
}
