<?php

namespace ContainerD5OMkT4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDocumentsControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XqlcQlt.App\Controller\DocumentsController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XqlcQlt.App\\Controller\\DocumentsController::delete()'] = ($container->privates['.service_locator.XqlcQlt'] ?? $container->load('get_ServiceLocator_XqlcQltService'))->withContext('App\\Controller\\DocumentsController::delete()', $container);
    }
}
