<?php

namespace ContainerD5OMkT4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProjetsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.scWB.EP.App\Entity\Projets' shared service.
     *
     * @return \App\Entity\Projets
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.scWB.EP": it needs an instance of "App\\Entity\\Projets" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
