<?php

namespace ContainerD5OMkT4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProjetsEtapesTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\ProjetsEtapesType' shared autowired service.
     *
     * @return \App\Form\ProjetsEtapesType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/ProjetsEtapesType.php';

        return $container->privates['App\\Form\\ProjetsEtapesType'] = new \App\Form\ProjetsEtapesType();
    }
}
