<?php

namespace ContainerTST5q4y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProjetsControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.scWB.EP.App\Controller\ProjetsController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.scWB.EP.App\\Controller\\ProjetsController::edit()'] = ($container->privates['.service_locator.scWB.EP'] ?? $container->load('get_ServiceLocator_ScWB_EPService'))->withContext('App\\Controller\\ProjetsController::edit()', $container);
    }
}
