<?php

namespace ContainerVR5aqyh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IBo63WbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iBo63Wb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iBo63Wb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'etape' => ['privates', '.errored..service_locator.iBo63Wb.App\\Entity\\Etapes', NULL, 'Cannot autowire service ".service_locator.iBo63Wb": it needs an instance of "App\\Entity\\Etapes" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'etape' => 'App\\Entity\\Etapes',
        ]);
    }
}
