<?php

namespace ContainerVR5aqyh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEtapesControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iBo63Wb.App\Controller\EtapesController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iBo63Wb.App\\Controller\\EtapesController::edit()'] = ($container->privates['.service_locator.iBo63Wb'] ?? $container->load('get_ServiceLocator_IBo63WbService'))->withContext('App\\Controller\\EtapesController::edit()', $container);
    }
}
