<?php

namespace ContainerVR5aqyh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEtapesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.iBo63Wb.App\Entity\Etapes' shared service.
     *
     * @return \App\Entity\Etapes
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.iBo63Wb": it needs an instance of "App\\Entity\\Etapes" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
