<?php

namespace ContainerVR5aqyh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProjetsControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ProjetsController' shared autowired service.
     *
     * @return \App\Controller\ProjetsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ProjetsController.php';

        $container->services['App\\Controller\\ProjetsController'] = $instance = new \App\Controller\ProjetsController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\ProjetsController', $container));

        return $instance;
    }
}
