<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTST5q4y\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTST5q4y/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTST5q4y.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTST5q4y\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTST5q4y\App_KernelDevDebugContainer([
    'container.build_hash' => 'TST5q4y',
    'container.build_id' => 'd624f92c',
    'container.build_time' => 1772102873,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTST5q4y');
