<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVR5aqyh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVR5aqyh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVR5aqyh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVR5aqyh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVR5aqyh\App_KernelDevDebugContainer([
    'container.build_hash' => 'VR5aqyh',
    'container.build_id' => '20cc2b5c',
    'container.build_time' => 1772098069,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVR5aqyh');
