<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.544b3ba4.js',
                '/build/799.39e35deb.js',
                '/build/app.b3c632b4.js',
            ],
            'css' => [
                '/build/799.34a558d5.css',
                '/build/app.68f5f8b2.css',
            ],
        ],
    ],
],

]];
